@startuml

'添加进去的主要代码：
 '1.ReceiverList rl = mRegisteredReceivers.get(receiver.asBinder());
 'ReceiverList类的定义如下,
 '"final class ReceiverList extends ArrayList<BroadcastFilter>"
 '里面的数据类型BroadcastFilter，定义如下，
 '"final class BroadcastFilter extends IntentFilter",
 '即BroadcastFilter 就是 IntentFilter。
 '
 'mRegisteredReceivers
 'key为 IIntentReceiver对应的Binder，
 'value为 对应的ReceiverList。
 '
 '2.rl.app.receivers.add(rl);
 '
 '3.mRegisteredReceivers.put(receiver.asBinder(), rl);
 '
 '4.BroadcastFilter bf = new BroadcastFilter(filter, rl, callerPackage,
 '                      permission, callingUid, userId, instantApp, visibleToInstantApps);
 '5.mReceiverResolver.addFilter(bf);'

class AMS{
{field} HashMap<IBinder, ReceiverList> mRegisteredReceivers
{field} IntentResolver<BroadcastFilter, BroadcastFilter> mReceiverResolver
}
note right of AMS
属性 mReceiverResolver 的作用，
后面梳理到再分析。
end note

note bottom of AMS
属性 mRegisteredReceivers：
Keeps track of all IIntentReceivers that have been registered for broadcasts.
Hash keys are the receiver IBinder, hash value is a ReceiverList.

即：
一个客户端的IIntentReceiver转换的Binder对象，拥有一个
IntentFilter的列表。
这是可以想象到的，即一个Context和BroadcastReceiver的二元组，
唯一确定一个IIntentReceiver，而这个二元组是可以添加多个
IntentFilter的哈。
end note

IIntentReceiver "1" -- "1" ReceiverList : one have one
note bottom of ReceiverList
类头的注释：
A receiver object that has registered for one or more broadcasts.
The ArrayList holds BroadcastFilter objects.

即：
一个IIntentReceiver对应的BroadcasrReceiver，
可以注册一个或多个广播，亦即会有一个或多个广播的intentFilter,
此列表即为存储它们而用。
end note

class IIntentReceiver{
   IBinder asBinder()
}
IIntentReceiver --|> Binder
Binder ..|> IBinder

ArrayList <|-- ReceiverList

class ArrayList<? extends BroadcastFilter>{
}

ArrayList "1" *-- "many" BroadcastFilter : have many >

BroadcastFilter --|> IntentFilter : extends

note bottom of IntentFilter
Structured description of Intent values to be matched.  An IntentFilter can
match against actions, categories, and data (either via its type, scheme,
and/or path) in an Intent.  It also includes a "priority" value which is
used to order multiple matching filters.
end note

@enduml